apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: bwbble.dataprep
spec:
  version: v1
  group: bwbble
  scope: Namespaced
  names:
    singular: dataprep
    plural: datapreps
    kind: DataPrep
    shortNames:
      - dp
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: bwbble.align
spec:
  version: v1
  group: bwbble
  scope: Namespaced
  names:
    singular: align
    plural: aligns
    kind: Align
    shortNames:
      - al
